#PRODUCERS
tommy = Producer.create!(name: "Tommy Showbiz")
sally = Producer.create!(name: "Sally Showbiz")
jimmy = Producer.create!(name: "Jimmy Showbiz")
bobby = Producer.create!(name: "Bobby Showbiz")
suzie = Producer.create!(name: "Suzie Showbiz")
barb = Producer.create!(name: "Barb Showbiz")


#GENRES
horror = Genre.create!(name: "Horror")
drama = Genre.create!(name: "Drama")
fantasy = Genre.create!(name: "Fantasy")
reality = Genre.create!(name: "Reality")
comedy = Genre.create!(name: "Comedy")



#DRAMA TROPES
achilles = Trope.create!(name: "Achilles Heel", description: "A seemingly invulnerable character has a single weakness", genre: drama)
always_murder = Trope.create!(name: "Always Murder", description: "By the end of the episode, someone is going to die", genre: drama)
one_man = Trope.create!(name: "As Long As There Is One", description: "A single courageous individual remains to resist the Big Bad's final takeover, inspiring their fellow citizens to take up arms", genre: drama)
big_word = Trope.create!(name: "Big Word Shout", description: "A character shouts a single word very loudly, usually 'NO' or 'WHY' or 'NEVER'", genre: drama)
chosen_one = Trope.create!(name: "The Chosen One", description: "A single individual is chosen or prophecied to attain heroic heights", genre: drama)
finger_twitch = Trope.create!(name: "Finger-Twitching Revival", description: "An unconscious character's finger gives a feeble twitch, heralding a return to life", genre: drama)
inspector = Trope.create!(name: "The Inspector is Coming", description: "An influential or otherwise authoritative critic or inspector is imminently arriving at the heroes' establishment", genre: drama)
lonely = Trope.create!(name: "Lonely Piano Piece", description: "Is the hero losing the battle against the villain? Has horrible news about a beloved character just been revealed? Cue the Lonely Piano Piece", genre: drama)
mysterious_parent = Trope.create!(name: "Mysterious Parent", description: "A protagonist's missing parent, vaguely alluded to until now, is suddenly revealed, with shocking implications", genre: drama)
non_sequitur = Trope.create!(name: "Notable Non Sequitur", description: "Any time a character mentions an unrelated piece of information off the cuff, like 'Sorry I'm late, my car was stolen,' it is guaranteed to become relevant later in the episode", genre: drama)
operation = Trope.create!(name: "Operation Game of Doom", description: "The hero must remove something from a container VERY carefully", genre: drama)
off_the_table = Trope.create!(name: "Off The Table", description: "An offer is extended to the hero and subsequently rejected. Later on, the hero attempts to take the deal, but is rebuffed. It is Off The Table", genre: drama)
just_a_dream: Trope.create!(name: "It Was A Dream the Whole Time", description: "It was a dream the whole time", description: drama)
please = Trope.create!(name: "Please, I'll Do Anything!", description: "Someone says the phrase 'Please, I'll do anything!', and is replied to with '... Anything?'", genre: drama)
punch = Trope.create!(name: "Punch A Wall", description: "Things are going poorly. The hero punches a wall", genre: drama)
you_suck = Trope.create!(name: "The Reason You Suck Speech", description: "Someone delivers a speech outlining exactly what's wrong with another character", genre: drama)
slow_clap = Trope.create!(name: "Slow Clap", description: "A single person starts to clap slowly, and everyone joins in", genre: drama)
crowd_chant = Trope.create!(name: "Crowd Chant", description: "A crowd chants something", genre: drama)
fetal_position = Trope.create!(name: "Troubled Fetal Position", description: "A character under extreme duress curls up into a ball", genre: drama)
take_it_back = Trope.create!(name: "Take Back Your Gift", description: "A gift given to a character earlier in the show is returned with hostility after a betrayal", genre: drama)

#COMEDY TROPES
montage = Trope.create!(name: "Time for a Montage", description: "Is there too much work to do? Has the hero finally accepted their quest? Is the broken-down establishment in need of a fix-up? Time for a montage", genre: comedy)
barricade = Trope.create!(name: "Absurdly Ineffective Barricade", description: "A constructed barricade proves laughably ineffectual", genre: comedy)
thats_what_she_said = Trope.create!(name:
"That's What She Said", description: "Somebody says 'that's what she said'", genre: comedy)
clown_car = Trope.create!(name: "Clown Car", description: "A vehicle holds way more occupants than it should", genre: comedy)
emergency_services = Trope.create!(name: "Acquainted With Emergency Services", description: "Somebody has been in trouble often enough that they're known to emergency services by name", genre: comedy)
faceplant = Trope.create!(name:"Faceplant", description:"Somebody faceplants in a comical way", genre: comedy)
freudian_slip = Trope.create!(name: "Freudian Slip", description: "Somebody says one thing but means their mother", genre: comedy)
funny_foreigner = Trope.create!(name: "Funny Foreigner", description: "A stranger from a strange land has customs, behaviors, or an accent that are played for laughs", genre: comedy)
ambulance_cut = Trope.create!(name: "Cut to Ambulance", description: "A character is doing something dangerous, suggesting a cunning plan that can't possibly go wrong, or eating something strange, and we cut to an Ambulance flying down the street", genre: comedy)
helium_speech = Trope.create!(name: "Helium Speech", description: "Somebody inhales helium and their voice is made comically high", genre: comedy)
lousy_t_shirt = Trope.create!(name: "Lousy T-Shirt", description: "Someone is wearing a t-shit that says they did something and all they got was this lousy t-shirt", genre: comedy)
diet_coke = Trope.create!(name: "And A Diet Coke", description: "Someone orders an absurd amount of unhealthy food 'and a diet coke'", genre: comedy)
standing_right_here = Trope.create!(name: "I'm Standing Right Here", description: "Two characters are having a private conversation about a third character, who happens to be standing right there", genre: comedy)
voice_crack = Trope.create!(name: "Inopportune Voice Cracking", description: "Someone's voice cracks at the worst possible moment", genre: comedy)
card_game = Trope.create!(name: "Lost Her in A Card Game", description: "Someone says they've lost something implausible in a card game", genre: comedy)
late_to_punchline = Trope.create!(name: "Late to the Punchline", description: "Someone understands the punchline of a joke way after the joke as been made", genre: comedy)
paper_thin_disguise = Trope.create!(name:"Paper-Thin Disguise", description: "Someone dons a disguise that is easily seen through", genre: comedy)
my_sensors_indicate = Trope.create!(name: "My Sensors Indicate", description: "A robotic character says their sensors indicate something extremely obvious", genre: comedy)
x_called = Trope.create!(name: "X Called, They Want Their Y Back", description: "A character is told that someone or something called, and they want whatever the character is wearing back", genre: comedy)
wacky_proposal = Trope.create!(name: "Wacky Proposal", description: "Someone proposes in a truly wacky way", genre: comedy)
vomit_chain_reaction = Trope.create!(name: "Vomit Chain Reaction", description: "One character vomits, and soon so does everyone else", genre: comedy)


#FANTASY TROPES
elven_folk = Trope.create!(name: "Elven Folk", description: "We encounter a race of fair-skinned, elegant, fair folk", genre: fantasy)
back_from_the_dead = Trope.create!(name: "Back From the Dead", description: "Someone comes back from the dead", genre: fantasy)
big_bad_wolf = Trope.create!(name: "Big Bad Wolf", description: "A monstrous beast set on eating the protagonist", genre: fantasy)
curse = Trope.create!(name: "A Curse On You", description: "Someone is the target of an evil hex", genre = fantasy)
evil_matriarch = Trope.create!(name: "Evil Matriarch", description: "A dominant female character with evil intentions", genre: fantasy)
evil_sorcerer = Trope.create!(name: "Evil Sorcerer", description: "A powerful and nefarious magic user", genre: fantasy)
fairy_god_mother = Trope.create!(name: "Fairy God Mother", description: "A benevolent fairy who appears to benefit a woebegotten character", genre: fantasy)
forbidden_fruit = Trope.create!(name: "Forbidden Fruit", description: "A fruit that must not be eaten", genre: fantasy)
damsel_in_distress = Trope.create!(name: "Damsel in Distress", description: "She's fair of skin, she's noble of birth, and she's in deep trouble", genre: fantasy)
secret_royaly = Trope.create!(name: "Secret Royalty", description: "A character thought to be a lowly commoner is suddenly revealed to secretly be royalty", genre: fantasy)
happily_ever_after = Trope.create!(name: "Happily Ever After", decription: "After a long and turbulent journey, it all works out in the end", genre: fantasy)
true_name = Trope.create!(name: "I Know Your True Name", description: "A character's secret background is hinted at by a wise old witch", genre: fantasy)
merciful_minion = Trope.create!(name: "Merciful Minion", description: "The main villain's underling is revealed to have a soft spot after all", genre: fantasy)
noble_fugitive = Trope.create!(name: "Noble Fugitive", description: "A member of the royal family must go on the run and is hunted", genre: fantasy)
knight_in_shining_armor = Trope.create!(name: "Knight in Shining Armor", description: "A noble, usually handsome knight who is pure of heart and good with a sword", genre: fantasy)
robin_hood = Trope.create!(name: "Just Like Robin Hood", description: "A character who steals from the rich and gives to the poor", genre: fantasy)
journey_to_mount_doom = Trope.create!(name: "Journey to Mount Doom", description: "A globe-trotting quest by a band of heroes on a mission that takes them across the land", genre: fantasy)
lost_woods = Trope.create!(name:"The Lost Woods", description: "A dark deep forest with many hidden dangers", genre: fantasy)
rags_to_riches = Trope.create!(name: "Rags to Royalty", description: "A character starts out with humble origins but ascends to the throne by the end of the story", genre: fantasy)
royal_brat = Trope.create!(name: "Royal Brat", description: "A character of royal blood is an absolute nightmare", genre: fantasy)

#HORROR TROPES
zombies = Trope.create!(name: "Zombie Apocalypse", description: "The dead have risen", genre: horror)
abandoned_hospital = Trope.create!(name: "Abandoned Hospital", description: "Once a place of healing and medicine, a creepy old hospital is long-abandoned", genre: horror)
alien_abduction = Trope.create!(name: "Alien Abduction", description: "Characters are abducted by visitors from another world", genre: horror)
blood_bath = Trope.create!(name: "Blood Bath", description: "An evil character has a bathtub full of blood", genre: horror)
bloody_handprint = Trope.create(name: "Bloody Handprint", description: "A character finds a handprint made in blood", genre: horror)
body_host = Trope.create!(name: "Body and Host", description: "Someone's body is hijacked by a symbiote, parasite, or other invasive visitor", genre: horror)
buried_alive = Trope.create!(name: "Buried Alive", description: "Someone is buried alive", genre: horror)
inside_the_house = Trope.create!(name: "The Calls Are Coming From Inside The House", description: "Threatening telephone calls are revealed to be coming from INSIDE THE HOUSE", genre: horror)
creepy_child = Trope.create!(name: "Creepy Child", description: "They're just a kid... But boy are they creepy", genre: horror)
crusty_caretaker = Trope.create!(name: "Crusty Caretaker", description: "A decrepit old groundskeeper is the only person at the crumbling mansion", genre: horror)
dark_lord = Trope.create!(name: "Dark Lord on Life Support", description: "The villain in charge of all the other villains is an ailing old man hooked up to nefarious machines", genre: horror)
the_woods = Trope.create!(name: "Don't Go in the Woods", description: "Characters are told that, whatever they don't, they shouldn't go in the woods", genre: horror)
demonic_doll = Trope.create!(name: "Demonic Doll", description: "It's tiny, it's frilly, and it's filled with demonic energy" genre: horror)
lab_accident = Trope.create!(name: "Freak Lab Accident", description: "Something in a scientific experiment goes horribly wrong", genre: horror)
headless_horseman = Trope.create!(name:"Headless Horseman", description: "A decapitated harbinger of doom", genre: horror)
ghost_hitchhiker = Trope.create!(name:"Ghost Hitchhiker", description: "A seemingly innocuous hitchhiker has a ghostly background", genre: horror)
mad_scientist = Trope.create!(name: "Mad Scientist", description: "A villain who uses his brilliant scientific mind for nefarious purposes", genre: drama)
lets_split_up = Trope.create!(name: "Let's Split Up", description: "The group splits up", genre: horror)
evil_clown = Trope.create!(name: "Evil Clown", description: "A clown who is evil", genre: horror)
murderous_mannequin = Trope.create!(name: "Murderous Mannequin", description: "It's sick of displaying clothes. Now it's out for blood", genre: horror)
scare_chord = Trope.create!(name: "Scare Chord", description: "The chord that gets played whenever something scary happens", genre: horror)


#REALITY TROPES
back_for_finale = Trope.create!(name: "Back for the Finale", description: "A contestant eliminated in previous rounds comes back for the finale", genre: reality)
brutal_honesty = Trope.create!(name: "Brutal Honesty", description: "One contestant gives another one a double-dose of hard truths", genre: reality)
confession_cam = Trope.create!(name: "Confession Cam", description: "Someone says what they really think on the Confession Cam", genre: reality)
catfight = Trope.create!(name: "Catfight", description: "Two female contestants get into a scrap", genre: reality)
eliminated = Trope.create!(name: "Elimination Catchphrase", description: "Now sashay away", genre: reality)
everyone = Trope.create!(name: "Everyone Meets Everyone", description: "Our contestants get to know each other", genre: reality)
mansion = Trope.create!(name: "Reality TV Mansion", description: "Our contestants live in a mansion", genre: reality)
shocking_elimination = Trope.create!(name: "Shocking Elimination", description: "Someone you never expected would get the gone is eliminated from the show", genre: reality)
competition = Trope.create!(name: "This is a Competition", description: "Someone says 'This is a competition'", genre: reality)
mean_brit = Trope.create!(name: "The Mean Brit", description: "The show has a mean British cast member", genre: reality)
make_friends = Trope.create!(name: "I'm Not Here to Make Friends", description: "Someone says the phrase 'I'm not here to make friends'", genre: reality)
celebrity_edition = Trope.create!(name: "Celebrity Edition", description: "It's the same show, but this time, with celebrities", genre: reality)


#ACTORS
robert = Actor.create!(name: "Robert De Niro", a_list: true)
jack = Actor.create!(name: "Jack Nicholson", a_list: true)
tom = Actor.create!(name: "Tom Hanks", a_list: true)
leo = Actor.create!(name: "Leonardo DiCaprio", a_list: true)
