tommy = Producer.create(name: "Tommy Showbiz")
sally = Producer.create(name: "Sally Showbiz")

horror = Genre.create(name: "Horror")
drama = Genre.create(name: "Drama")
fantasy = Genre.create(name: "Fantasy")
reality = Genre.create(name: "Reality")
gameshow = Genre.create(name: "Gameshow")
comedy = Genre.create(name: "Comedy")
documentary = Genre.create(name: "Genre")
